# Generated by Django 5.0.4 on 2024-05-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('review', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
