# Generated by Django 5.0.4 on 2024-05-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('messages', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
