# Generated by Django 5.0.4 on 2024-05-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_remove_chat_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='username',
        ),
    ]
