# Generated by Django 5.0.4 on 2024-05-18 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_review_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chat',
        ),
    ]
