# Generated by Django 5.0.4 on 2024-05-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_rename_contacts_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
